posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('home/', views.TweetListView.as_view(), name='home'),
    # path('home/', views.home, name='home'),
    path('add-tweet/', views.TweetCreateView.as_view(), name='add-tweet'),
    # path('add-tweet/', views.addTweet, name='add-tweet'),
    # path('my-tweets/', views.TweetListView.as_view(), name='my-tweets'),
    # path('my-tweets/', views.myTweets, name='my-tweets'),
]

twitter_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('', include('posts.urls'))
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),
]

posts/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse

# Create your models here.

class Post(models.Model):
    text = models.CharField(max_length=200)
    date_published = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)

    def __str__(self):
        return self.text

    def get_absolute_url(self):
        return reverse("posts:home")
    
    def date_today(self):
        self.date_published = timezone.now()
        self.save()

    class Meta:
        ordering = ['-date_published']

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from posts.models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = "__all__"

posts/views.py
from django.shortcuts import render
# from django.urls import reverse_lazy, reverse
from django.views import generic
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from posts.models import Post
from users.forms import PostForm

# Create your views here.

# def addTweet(request):
#     if request.method == 'POST':
#         form = PostForm(request.POST or None) 
#         if form.is_valid(): 
#             form.save()
#             posts = Post.objects.all()
#             return render(request, 'my-tweets.html', {'posts': posts})
#     else:
#         form_class = PostForm
#     return render(request, "add-tweet.html", {
#         'form': form_class,})

class TweetCreateView(LoginRequiredMixin, CreateView):
    model = Post
    template_name = 'add-tweet.html'
    fields = ['text','author']
    exclude = ('author') 

    def form_vaild(self, form): 
        form.instance.author=self.request.user
        return super().form_valid(form)



# def myTweets(request):
#     text_input = request.POST.get('text')
#     date_published_input = request.POST.get('date_published')
#     author_input = request.POST.get('author')
#     Post.objects.create(text=text_input, date_published=date_published_input, author=author_input)
#     items = Post.objects.all()
#     context = {'content': items}
#     return render(request, 'my-tweets.html', context)

class TweetListView(generic.ListView):
    model = Post
    template_name = 'home.html'
    # context_object_name = 'posts'
    # ordering = ['-date_published']

users/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.urls import reverse_lazy, reverse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import logout

# Create your views here.

class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    template_name = 'signup.html'
    success_url = reverse_lazy('login')


class LoginView(generic.DetailView):
    template_name = 'login.html'
    success_url = reverse_lazy('home')


def logout_view(request):
    logout(request)
    return redirect('login')

templates/add-tweet.html
{% extends "base.html" %}

{% block content %}
<body>
	<div class="body">
		<h3>Add A Tweet</h3>
		<br>
		<form method="post" enctype="multipart/form-data" action="{% url 'posts:add-tweet' %}">
			{% csrf_token %}
			{{ form.as_p }}
            {% comment %} <input class="input-box" id="text" name="text" type="text" placeholder="Type chirp here...">
            <br><br>
            <input class="input-box" id="date_published" name="date_published" type="date" placeholder="today's date"><br><br> {% endcomment %}
            <button type="submit">submit</button>
			
		</form>
	</div>
</body>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <title>{% block title %}Chirp{% endblock %}</title>
</head>
<body>
    <div class="header">
        <h1 class="app-name">Chirp</h1>
    </div>
    <ul class="nav-top">
        <li><a href="{% url 'posts:home' %}">Home</a></li>
        {% if user.is_authenticated %}
        {% comment %} <li><a href="{% url 'posts:my-tweets' %}">My Tweets</a></li> {% endcomment %}
        <li><a href="{% url 'posts:add-tweet' %}">Add Tweet</a></li>
        <li><a href="{% url 'users:logout' %}">Logout, <em>{{ user.username }}</em></a></li>
        {% endif %}
    </ul>
    
	{% block content %}
	{% endblock content %}
    </div>

</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block content %}
<body>
    <div>
        {% if user.is_authenticated %}
        <div class="body">
            <h2>Tweets by <em>{{ user.username }}</em></h2>
            {% for post in object_list %}
                <p>{{ post.text }}</p>
                <p>{{ post.date_published }}</p>
                <p><em>by: {{ post.author.username }}</em></p>
                <br><br>
            {% endfor %}
        </div>
        
        {% else %}
        <h2>Welcome</h2>
        <p>You are not logged in. Please <strong><a href="{% url 'users:login' %}">login</a></strong> or <strong><a href="{% url 'users:signup' %}">sign up</a></strong>.</p>
        {% endif %}
    </div>
</body>
{% endblock %}

templates/signup.html
{% extends 'base.html' %}

{% block content %}
<body>
  <div class="body">
    <h2>Account Registration</h2>
    <form class="form-border" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">sign up</button><br>
    </form>
    <p><strong><em>If you already have an account <a href="{% url 'users:login' %}" target="blank"><strong>login</strong></a> instead.</em></strong></p>
  </div>
</body>
{% endblock %}